# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\x10\x63om.example.grpc\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"/\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t2\xa6\x01\n\x07Greeter\x12J\n\x08SayHello\x12\x1e.com.example.grpc.HelloRequest\x1a\x1c.com.example.grpc.HelloReply\"\x00\x12O\n\x0bStreamHello\x12\x1e.com.example.grpc.HelloRequest\x1a\x1c.com.example.grpc.HelloReply\"\x00\x30\x01\x42%\n\x10\x63om.example.grpcB\x0fHelloWorldProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.example.grpcB\017HelloWorldProtoP\001'
  _globals['_HELLOREQUEST']._serialized_start=38
  _globals['_HELLOREQUEST']._serialized_end=84
  _globals['_HELLOREPLY']._serialized_start=86
  _globals['_HELLOREPLY']._serialized_end=133
  _globals['_GREETER']._serialized_start=136
  _globals['_GREETER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
