// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.example.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\020com.example.grpc\".\n\014" +
      "HelloRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010language\030\002" +
      " \001(\t\"/\n\nHelloReply\022\017\n\007message\030\001 \001(\t\022\020\n\010l" +
      "anguage\030\002 \001(\t2\246\001\n\007Greeter\022J\n\010SayHello\022\036." +
      "com.example.grpc.HelloRequest\032\034.com.exam" +
      "ple.grpc.HelloReply\"\000\022O\n\013StreamHello\022\036.c" +
      "om.example.grpc.HelloRequest\032\034.com.examp" +
      "le.grpc.HelloReply\"\0000\001B%\n\020com.example.gr" +
      "pcB\017HelloWorldProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", "Language", });
    internal_static_com_example_grpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_HelloReply_descriptor,
        new java.lang.String[] { "Message", "Language", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
